# Generated by Django 5.0.3 on 2024-03-31 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task3", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="margin",
            new_name="marja",
        ),
        migrations.RemoveField(
            model_name="product",
            name="encrypted_margin",
        ),
        migrations.RemoveField(
            model_name="product",
            name="encrypted_package_code",
        ),
        migrations.RemoveField(
            model_name="product",
            name="encrypted_price",
        ),
        migrations.AddField(
            model_name="product",
            name="title",
            field=models.CharField(default=1, max_length=123),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="package_code",
            field=models.CharField(max_length=10),
        ),
    ]
